/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unesp.tecnprogramacao.jogodavelhafront.telas;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eduks
 */
public class CriarConta extends javax.swing.JPanel {

    /**
     * Creates new form CriarConta
     */
    public CriarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_JogoDaVelha = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        btn_Voltar = new javax.swing.JButton();
        btn_CriarConta = new javax.swing.JButton();

        lbl_JogoDaVelha.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_JogoDaVelha.setText("Jogo da Velha");

        txt_Usuario.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txt_Usuario.setText("Digite o seu usuário...");

        btn_Voltar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btn_Voltar.setText("Voltar");
        btn_Voltar.setActionCommand("J");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_CriarConta.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btn_CriarConta.setText("Criar usuário");
        btn_CriarConta.setActionCommand("J");
        btn_CriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 238, Short.MAX_VALUE)
                .addComponent(lbl_JogoDaVelha)
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(btn_CriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(163, 163, 163)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_JogoDaVelha)
                .addGap(54, 54, 54)
                .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btn_Voltar)
                .addGap(63, 63, 63))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(342, Short.MAX_VALUE)
                    .addComponent(btn_CriarConta)
                    .addGap(62, 62, 62)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.setContentPane(new Inicial().getContentPane());
        janela.revalidate();
        janela.repaint();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void btn_CriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CriarContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CriarConta;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JLabel lbl_JogoDaVelha;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
